name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: "Installing dependencies"
        run: npm ci

      - name: "Cache Node Modules"
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ matrix.node-version }}-${{ github.run_id }}
          restore-keys: |
            npm-${{ matrix.node-version }}

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # ⚠️ Code checkout karna zaroori hai!
      - name: "Build Command"
        run: npm run build --if-present

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # ⚠️ Code checkout karna zaroori hai!
      - name: "Running test cases"
        run: npm run test
